### ISSUE TITLE
sklearn models compatibility issue

### ISSUE THREAD

**Issue by cr019283** [jpmml/jpmml-hive#3]
I trained a random forest model in sklearn; then exported it to pickle and generated pmml with converter-executable-1.2-SNAPSHOT.jar (jpmml-sklearn).

However, when I use generated pmml with jpmml-hive, I come across two issues:
1) generated datatype is float, which causes problems for jpmml-hive:

FAILED: SemanticException [Error 10014]: Line 4:7 Wrong arguments '1': com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: http://www.dmg.org/PMML-4_3

I can solve this problem by manually editing pmml and changing version to 4.2 and by changing also:

<DataField name="x1" optype="continuous" dataType="float"/>

to

<DataField name="x1" optype="continuous" dataType="double"/>

2) However, the I run into another problem:

	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:539)
	... 9 more
Caused by: org.jpmml.evaluator.TypeCheckException: Expected org.jpmml.evaluator.HasProbability, but got org.jpmml.evaluator.ClassificationMap (ClassificationMap{type=VOTE, vote_entries=[0=0.21212121212121213, 1=0.18181818181818182, 2=0.3333333333333333, 3=0.2727272727272727]})
	at org.jpmml.evaluator.OutputUtil.asResultFeature(OutputUtil.java:848)
	at org.jpmml.evaluator.OutputUtil.getProbability(OutputUtil.java:478)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:182)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:120)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:88)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:230)
	at org.jpmml.hive.PMMLUtil.evaluateComplex(PMMLUtil.java:226)
	at com.my.test.pmml.hive.udf.RandomForestClassifier.evaluate(RandomForestClassifier.java:16)
	at org.apache.hadoop.hive.ql.exec.ExprNodeGenericFuncEvaluator._evaluate(ExprNodeGenericFuncEvaluator.java:166)
	at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:77)
	at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:65)
	at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:79)

This is a rather basic usage of this lib, but it has already taken me a considerably amount of time. Is there an easy fix to it? 

Perhaps, if I could force jpmml-sklearn to generate pmml version 4.2, it could be mitigated.

**Comment by vruusmann** [comment]
The JPMML-Hive project was last updated on 17th of December, **2014** (that's more than **two years** ago). As such, it includes the JPMML-Evaluator version 1.1.13, which is badly outdated.

All your issues would be resolved if you upgraded the JPMML-Evaluator dependency to something more recent. For example, PMML 4.3 support is available starting from JPMML-Evaluator version 1.3.0.

I have no interest in maintaining the JPMML-Hive project. Should probably take it private (or delete altogether) in order to avoid confusing people in the future.
